name: Docker Build and Push

on:
  push:
    tags:
      - "v*"

env:
  APP_NAME: gh-proxy-go

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set GHCR username
        run: |
          echo "GITHUB_USER=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ env.GITHUB_USER }}/${{ env.APP_NAME }}:latest
            ghcr.io/${{ env.GITHUB_USER }}/${{ env.APP_NAME }}:${{ github.ref_name }}
            ${{ env.DOCKERHUB_USER }}/${{ env.APP_NAME }}:latest
            ${{ env.DOCKERHUB_USER }}/${{ env.APP_NAME }}:${{ github.ref_name }}
